[package]
name = "cqrl"
version = "0.1.0"
edition = "2021"

[dependencies]
parser = { version = "0.1.0", path = "parser" }
persistence = {version = "0.1.0", path = "persistence" }
errors = {version = "0.1.0", path = "errors" }
pest = "2.7.15"

[workspace]
members = [ "errors","parser", "persistence"]
