[package]
name = "cqrl"
version = "0.1.0"
edition = "2021"

[dependencies]
parser = { version = "0.1.0", path = "parser" }
errors = {version = "0.1.0", path = "errors" }
clap = { version = "4.5.26", features = ["derive"] }
serde_json = "1.0.137"
tokio = { version = "1.43.0", features = ["full"] }
futures = "0.3.31"
async-nats = "0.39.0"
mongodb = { version = "3.2.2", features = ["sync"] }
cloudevents-sdk = "0.8.0"
openapiv3 = "2.0.0"
indexmap = "2.9.0"
serde = "1.0.219"
chrono = "0.4.40"
ulid = "1.2.1"
axum = "0.8.3"
hyper = "1.6.0"
regex = "1.11.1"
contexts = "0.1.0"
actix-web = { version = "4.11.0", features = ["actix-tls"] }
async-trait = "0.1.88"
ctrlc = "3.4.7"
tracing = { version = "0.1.41", features = ["log"] }
tracing-subscriber = { version = "0.3.20", features = ["env-filter", "json"] }
crc64 = "2.0.0"
scylla = "1.1.0"
opentelemetry-otlp = { version = "0.30.0", features = ["grpc-tonic"] }
opentelemetry_sdk = { version = "0.30.0", features = ["tokio"] }
opentelemetry-appender-tracing = "0.30.0"
opentelemetry = "0.30.0"
clap-serde-derive = "0.2.1"
toml = "0.8.23"
jsonwebtoken = "9.3.1"
reqwest = { version = "0.12.22", features = ["rustls-tls"], default-features = false }
nkeys = "0.4.5"

[workspace]
members = ["errors","parser"]

[[ bin ]]
name = "cqrl"
path = "./src/main.rs"
