[package]
name = "cqrl"
version = "0.1.0"
edition = "2021"

[dependencies]
parser = { version = "0.1.0", path = "parser" }
errors = {version = "0.1.0", path = "errors" }
pest = "2.7.15"
clap = { version = "4.5.26", features = ["derive"] }
serde_json = "1.0.137"
tokio = { version = "1.43.0", features = ["full"] }
futures = "0.3.31"
async-nats = "0.39.0"
mongodb = "3.2.2"
cloudevents-sdk = "0.8.0"
openapiv3 = "2.0.0"
indexmap = "2.9.0"
serde = "1.0.219"
chrono = "0.4.40"
ulid = "1.2.1"
axum = "0.8.3"
hyper = "1.6.0"
regex = "1.11.1"
contexts = "0.1.0"
actix-web = "4.11.0"
async-trait = "0.1.88"
ctrlc = "3.4.7"

[workspace]
members = ["errors","parser"]

[[ bin ]]
name = "cqrl"
path = "./src/main.rs"
