version: "3.9"
networks:
  cqrl-network:
services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    networks:
      - cqrl-network
  nats-listener:
    image: natsio/nats-box:latest
    command: nats sub -s nats://nats:4222 "cqrl.command.>"
    networks:
      - cqrl-network
  mongo1:
    image: mongodb/mongodb-community-server:latest
    user: root
    command: --replSet rs0 --bind_ip 0.0.0.0 --port 27017
    healthcheck:
      test: cat /mongo-healthcheck.js | mongosh mongodb://localhost:27017/cqrl --quiet
      interval: 5s
      timeout: 30s
    volumes:
      - ./mongo-healthcheck.js:/mongo-healthcheck.js
    ports:
      - "27017:27017"
    networks:
      - cqrl-network
