/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * CQRL API
 * OpenAPI spec version: 1.0.0
 */
import {
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateQueryOptions,
  CreateQueryResult,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetQueryPostsParams,
  GetQueryTestParams,
  QueryInternalResponse,
  QueryNotfoundResponse,
  QueryPostsSuccessResponse,
  QueryTestSuccessResponse,
  QueryUnauthorizedResponse
} from '.././models';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




export const getQueryPosts = (
    params: GetQueryPostsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<QueryPostsSuccessResponse>> => {
    
    
    return axios.get(
      `/query/posts`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getGetQueryPostsQueryKey = (params: GetQueryPostsParams,) => {
    return [`/query/posts`, ...(params ? [params]: [])] as const;
    }

    
export const getGetQueryPostsQueryOptions = <TData = Awaited<ReturnType<typeof getQueryPosts>>, TError = AxiosError<QueryUnauthorizedResponse | QueryNotfoundResponse | QueryInternalResponse>>(params: GetQueryPostsParams, options?: { query?:CreateQueryOptions<Awaited<ReturnType<typeof getQueryPosts>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQueryPostsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQueryPosts>>> = ({ signal }) => getQueryPosts(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getQueryPosts>>, TError, TData> & { queryKey: QueryKey }
}

export type GetQueryPostsQueryResult = NonNullable<Awaited<ReturnType<typeof getQueryPosts>>>
export type GetQueryPostsQueryError = AxiosError<QueryUnauthorizedResponse | QueryNotfoundResponse | QueryInternalResponse>



export function createGetQueryPosts<TData = Awaited<ReturnType<typeof getQueryPosts>>, TError = AxiosError<QueryUnauthorizedResponse | QueryNotfoundResponse | QueryInternalResponse>>(
 params: GetQueryPostsParams, options?: { query?:CreateQueryOptions<Awaited<ReturnType<typeof getQueryPosts>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ): CreateQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetQueryPostsQueryOptions(params,options)

  const query = createQuery(queryOptions ) as CreateQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



export const getQueryTest = (
    params: GetQueryTestParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<QueryTestSuccessResponse>> => {
    
    
    return axios.get(
      `/query/test`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }


export const getGetQueryTestQueryKey = (params: GetQueryTestParams,) => {
    return [`/query/test`, ...(params ? [params]: [])] as const;
    }

    
export const getGetQueryTestQueryOptions = <TData = Awaited<ReturnType<typeof getQueryTest>>, TError = AxiosError<QueryUnauthorizedResponse | QueryNotfoundResponse | QueryInternalResponse>>(params: GetQueryTestParams, options?: { query?:CreateQueryOptions<Awaited<ReturnType<typeof getQueryTest>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetQueryTestQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getQueryTest>>> = ({ signal }) => getQueryTest(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getQueryTest>>, TError, TData> & { queryKey: QueryKey }
}

export type GetQueryTestQueryResult = NonNullable<Awaited<ReturnType<typeof getQueryTest>>>
export type GetQueryTestQueryError = AxiosError<QueryUnauthorizedResponse | QueryNotfoundResponse | QueryInternalResponse>



export function createGetQueryTest<TData = Awaited<ReturnType<typeof getQueryTest>>, TError = AxiosError<QueryUnauthorizedResponse | QueryNotfoundResponse | QueryInternalResponse>>(
 params: GetQueryTestParams, options?: { query?:CreateQueryOptions<Awaited<ReturnType<typeof getQueryTest>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ): CreateQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetQueryTestQueryOptions(params,options)

  const query = createQuery(queryOptions ) as CreateQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}



