/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * CQRL API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Server rejected the command, something happened internally
 */
export type CommandInternalResponse = void;
