/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * CQRL API
 * OpenAPI spec version: 1.0.0
 */

export type GetQueryTestParams = {
/**
 * @pattern [0-9A-HJKMNP-TV-Z]{26}
 */
id?: string;
/**
 * @minimum 1
 * @maximum 100
 */
page_size?: number;
/**
 * @minimum 1
 */
page?: number;
};
