/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * CQRL API
 * OpenAPI spec version: 1.0.0
 */

export * from './commandBaddataResponse';
export * from './commandInternalResponse';
export * from './commandNewPostBody';
export * from './commandSuccessResponse';
export * from './commandUnauthorizedResponse';
export * from './commandUpdatePostBody';
export * from './getQueryPostsParams';
export * from './getQueryTestParams';
export * from './post';
export * from './postCommandNewPostParams';
export * from './postCommandUpdatePostParams';
export * from './postInput';
export * from './postUpdateInput';
export * from './queryInternalResponse';
export * from './queryNotfoundResponse';
export * from './queryPostsSuccessResponse';
export * from './queryTestSuccessResponse';
export * from './queryUnauthorizedResponse';