/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * CQRL API
 * OpenAPI spec version: 1.0.0
 */

export interface PostUpdateInput {
  /** @pattern [0-9A-HJKMNP-TV-Z]{26} */
  id: string;
  title?: string;
  body?: string;
}
