/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * CQRL API
 * OpenAPI spec version: 1.0.0
 */

/**
 * Server rejected the query, user not authorized to see that
 */
export type QueryUnauthorizedResponse = void;
