/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * CQRL API
 * OpenAPI spec version: 1.0.0
 */
import {
  createMutation
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  MutationFunction
} from '@tanstack/svelte-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CommandBaddataResponse,
  CommandInternalResponse,
  CommandNewPostBody,
  CommandSuccessResponse,
  CommandUnauthorizedResponse,
  CommandUpdatePostBody,
  PostCommandNewPostParams,
  PostCommandUpdatePostParams
} from '.././models';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




export const postCommandNewPost = (
    commandNewPostBody: CommandNewPostBody,
    params?: PostCommandNewPostParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CommandSuccessResponse>> => {
    
    
    return axios.post(
      `/command/new_post`,
      commandNewPostBody,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getPostCommandNewPostMutationOptions = <TError = AxiosError<CommandUnauthorizedResponse | CommandBaddataResponse | CommandInternalResponse>,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof postCommandNewPost>>, TError,{data: CommandNewPostBody;params?: PostCommandNewPostParams}, TContext>, axios?: AxiosRequestConfig}
): CreateMutationOptions<Awaited<ReturnType<typeof postCommandNewPost>>, TError,{data: CommandNewPostBody;params?: PostCommandNewPostParams}, TContext> => {

const mutationKey = ['postCommandNewPost'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postCommandNewPost>>, {data: CommandNewPostBody;params?: PostCommandNewPostParams}> = (props) => {
          const {data,params} = props ?? {};

          return  postCommandNewPost(data,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostCommandNewPostMutationResult = NonNullable<Awaited<ReturnType<typeof postCommandNewPost>>>
    export type PostCommandNewPostMutationBody = CommandNewPostBody
    export type PostCommandNewPostMutationError = AxiosError<CommandUnauthorizedResponse | CommandBaddataResponse | CommandInternalResponse>

    export const createPostCommandNewPost = <TError = AxiosError<CommandUnauthorizedResponse | CommandBaddataResponse | CommandInternalResponse>,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof postCommandNewPost>>, TError,{data: CommandNewPostBody;params?: PostCommandNewPostParams}, TContext>, axios?: AxiosRequestConfig}
 ): CreateMutationResult<
        Awaited<ReturnType<typeof postCommandNewPost>>,
        TError,
        {data: CommandNewPostBody;params?: PostCommandNewPostParams},
        TContext
      > => {

      const mutationOptions = getPostCommandNewPostMutationOptions(options);

      return createMutation(mutationOptions );
    }
    export const postCommandUpdatePost = (
    commandUpdatePostBody: CommandUpdatePostBody,
    params?: PostCommandUpdatePostParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CommandSuccessResponse>> => {
    
    
    return axios.post(
      `/command/update_post`,
      commandUpdatePostBody,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getPostCommandUpdatePostMutationOptions = <TError = AxiosError<CommandUnauthorizedResponse | CommandBaddataResponse | CommandInternalResponse>,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof postCommandUpdatePost>>, TError,{data: CommandUpdatePostBody;params?: PostCommandUpdatePostParams}, TContext>, axios?: AxiosRequestConfig}
): CreateMutationOptions<Awaited<ReturnType<typeof postCommandUpdatePost>>, TError,{data: CommandUpdatePostBody;params?: PostCommandUpdatePostParams}, TContext> => {

const mutationKey = ['postCommandUpdatePost'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postCommandUpdatePost>>, {data: CommandUpdatePostBody;params?: PostCommandUpdatePostParams}> = (props) => {
          const {data,params} = props ?? {};

          return  postCommandUpdatePost(data,params,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostCommandUpdatePostMutationResult = NonNullable<Awaited<ReturnType<typeof postCommandUpdatePost>>>
    export type PostCommandUpdatePostMutationBody = CommandUpdatePostBody
    export type PostCommandUpdatePostMutationError = AxiosError<CommandUnauthorizedResponse | CommandBaddataResponse | CommandInternalResponse>

    export const createPostCommandUpdatePost = <TError = AxiosError<CommandUnauthorizedResponse | CommandBaddataResponse | CommandInternalResponse>,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof postCommandUpdatePost>>, TError,{data: CommandUpdatePostBody;params?: PostCommandUpdatePostParams}, TContext>, axios?: AxiosRequestConfig}
 ): CreateMutationResult<
        Awaited<ReturnType<typeof postCommandUpdatePost>>,
        TError,
        {data: CommandUpdatePostBody;params?: PostCommandUpdatePostParams},
        TContext
      > => {

      const mutationOptions = getPostCommandUpdatePostMutationOptions(options);

      return createMutation(mutationOptions );
    }
    