name: Release Rust

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  cliff:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.changelog.outputs.version }}
      changelog: ${{ steps.changelog.outputs.content }}
      release_id: ${{ steps.create-release.outputs.result }}
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Generate a changelog
        id: changelog
        uses: orhun/git-cliff-action@4a4a951bc43fafe41cd2348d181853f52356bee7 # v4
        with:
          config: cliff.toml
          args: --bump --unreleased -s header
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Create release
        id: create-release
        uses: actions/github-script@v7
        env:
          VERSION: ${{ steps.changelog.outputs.version }}
          CHANGELOG: ${{ steps.changelog.outputs.content }}
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          result-encoding: string
          script: |
            const { VERSION, CHANGELOG } = process.env;

            const { owner, repo } = context.repo;

            const release = await github.rest.repos.createRelease({
              owner,
              repo,
              tag_name: VERSION,
              name: VERSION,
              body: CHANGELOG,
            });

            return release.data.id;

      - name: Create Full Changelog
        uses: orhun/git-cliff-action@4a4a951bc43fafe41cd2348d181853f52356bee7 # v4
        with:
          config: cliff.toml
          args: --bump
        env:
          OUTPUT: docs/CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit Changelog
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |-
          git config user.email "cqrl-release-bot@users.noreply.github.com"
          git config user.name "cqrl-release-bot"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git add docs/CHANGELOG.md
          git commit -m "update changelog"
          git push

  build:
    name: Build - ${{ matrix.platform.target }}
    runs-on: ${{ matrix.platform.runner }}
    needs:
      - cliff
    strategy:
      matrix:
        platform:
          - runner: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          - runner: ubuntu-22.04-arm
            target: aarch64-unknown-linux-gnu
          - runner: macos-latest
            target: x86_64-apple-darwin
          - runner: macos-latest
            target: aarch64-apple-darwin
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup Rust
        env:
          CARGO_TARGET: ${{ matrix.platform.target }}
        run: |
          rustup update
          rustup target add "$CARGO_TARGET"
      - name: Build binary
        env:
          CARGO_TARGET: ${{ matrix.platform.target }}
        run: |
          cargo build --release --target $CARGO_TARGET

      - name: Upload binary
        uses: actions/github-script@v7
        env:
          BINARY: target/${{ matrix.platform.target }}/release/cqrl
          RELEASE_ID: ${{ needs.cliff.outputs.version }}
          UPLOAD_ID: ${{ needs.cliff.outputs.release_id }}
          TARGET: ${{ matrix.platform.target }}
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const fs = require('fs');
            const { BINARY, RELEASE_ID, TARGET, UPLOAD_ID } = process.env;

            const { owner, repo } = context.repo;

            await github.rest.repos.uploadReleaseAsset({
              owner,
              repo,
              release_id: UPLOAD_ID,
              name: `cqrl-${RELEASE_ID}-${TARGET}`,
              data: fs.readFileSync(BINARY),
            });
